### ISSUE TITLE
can device in terminal ?

### ISSUE THREAD

**Issue by romanoLT** [jonans/jump_bms#1]
Hey @jonans thanks for the amazing work.
Would your opencandump script work if you are sniffing the full CAN bus with other device (light for example) - and thus are not acting like a terminal node?

**Comment by jonans** [comment]
canopendump works as an active node on the bus to dump another devices data table. If the light is canopen compatible and you know the node address it should work.

If you want to passively monitor communication between other devices it wont help.  You can use candump or cansniffer from the can-utils package for this.

**Comment by quantum-x** [comment]
Hi @jonans 
Thanks for your work on this.
Do you have any insight on how to determine the CAN Node address ?
I'm working on a similar battery system that communicates with CAN, but have been unable to determine if it speaks CANOpen or low-level CAN.

Thanks kindly
